version: '3'
services:
  sensors:
    build: sensor/
    command: python3 ./sensor.py
  controller:
    build: controller/
    command: python3 ./controller.py
    depends_on:
      - sensors
  manipulator:
    build: manipulator/
    command: python3 ./manipulator.py
    depends_on:
      - controller    
  webapp:
    build: .
    ports:
      - 5000:5000